### ISSUE TITLE
Value of x is unused

### ISSUE THREAD

**Issue by astrelsky** [mooncat-greenpy/Ghidra_GolangAnalyzerExtension#3]
https://github.com/mooncat-greenpy/Ghidra_GolangAnalyzerExtension/blob/f8d0edec0504c13dcecaf0b5be6826de49489c75/src/main/java/golanganalyzerextension/StructureManager.java#L609

Is this supposed to be used somewhere?

Also I would recommend only logging this if the debug option is set so the popup doesn't appear every time after running analysis on a non go program.

https://github.com/mooncat-greenpy/Ghidra_GolangAnalyzerExtension/blob/f8d0edec0504c13dcecaf0b5be6826de49489c75/src/main/java/golanganalyzerextension/GolangAnalyzerExtensionAnalyzer.java#L73

**Comment by mooncat-greenpy** [comment]
Thank you for your advice.
